version: "3.8"

services:
  nginx:
    image: nginx:1.23.0-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build: .
    # ports:
    #   - "3000-3001:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.15
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zeeshan
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:7.0.2

volumes:
  mongo-db:
